name = "FamaMacBeth"
uuid = "a379ddc0-9001-11e8-0fe1-85dd08ebdee6"
authors = ["Jeroen van Zundert <zundertj@gmail.com>"]
version = "0.0.1"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
