name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0.4, 1.1.1, 1.2.0-rc3, 1.3.0-alpha]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1.0.0
    - uses: julia-actions/setup-julia@latest
      with:
        version: ${{ matrix.julia-version }}
    - uses: julia-actions/julia-runtest@master
